# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InfiteeAnimation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InfiteeAnimation
  pod 'SnapKit'
  pod 'PullToRefreshKit'
  pod 'ESTabBarController-swift'
  pod 'LookinServer', :configurations => ['Debug']
  
  target 'InfiteeAnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InfiteeAnimationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
